language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.4.1
  - MRUBY_VERSION=2.1.2
  - MRUBY_VERSION=3.0.0
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf
script:
  - rake test
